name: Show Name and Surname
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run script
      run: |
        echo "Your name is [Artem Hrebeniuk]"
