name: Display First and Last Name

on:
  push:
    branches:
      - main

jobs:
  build-and-display:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run the script
        run: node script.js
